beginning quiz integration
Elao/elao_ pull request #398
Opened 2021-08-19 07:20 UTC by sludovicdelys

Started working on the integration for a quiz at the end of each article. Will be working on the checkboxes next.

2021-08-20 09:22 UTC, ameliedefrance commented
Cas de figure manquants : 

- [ ] Pour l'instant on a un quizz où plusieurs réponses sont possibles pour chaque question. On a pas le cas où l'auteur du quizz attend une seule réponse possible pour les questions. Il nous faudrait des [boutons radio](https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/radio) 
- [ ] L'utilisateur a terminé le quizz et il a fait des erreurs : il faut qu'il puisse voir quelles sont les réponses sur lesquelles il a fait des erreurs. Je propose qu'on prévoit un bloc de réponse en dessous de chaque question qui comporterait 
    - la réponse correcte
    - un petit indice visuel pour savoir si la réponse de l'utilisateur était correcte ou incorrecte (un emoji ?)

2021-08-20 09:23 UTC, ameliedefrance requested changes

2021-08-20 09:23 UTC, ameliedefrance commented on assets/scss/components/checkbox.scss
> + .checkbox pre {
En Sass, tu peux imbriquer tes sélecteurs : 

```
.quiz__details {
   ... 

   p { ... } 
}
```

2021-08-27 14:54 UTC, ameliedefrance requested changes

2021-08-30 14:36 UTC, ameliedefrance requested changes

2021-08-30 14:36 UTC, ameliedefrance commented on assets/scss/components/quiz.scss
> +  padding: 8.7em 6.2em;
```suggestion
  padding: 7em 5em 5em; 
```

2021-08-30 14:36 UTC, ameliedefrance commented on assets/scss/components/question.scss
> +    padding: .3em;
```suggestion
    margin: 0 0 .3em;
```

2021-08-30 14:36 UTC, ameliedefrance commented on assets/scss/components/quiz.scss
> +  flex: wrap;
```suggestion
```

2021-08-30 14:36 UTC, ameliedefrance commented on assets/scss/components/quiz.scss
> +  width: 150px;
```suggestion
```

2021-09-01 13:02 UTC, ameliedefrance approved these changes
Merci @sludovicdelys ✨ 🎉

2021-09-01 13:16 UTC, ogizanagi commented on templates/blog/article.html.twig
> +	<div class="quiz">
Attention il y a beaucoup trop de diffs d'indentation et changement non-liés à cette PR dans ce fichier. Certainement ton IDE qui a appliqué du formatting auto. En tous cas on éviter ce genre de changement massif non justifié car perturbe l'historique et risque de provoquer des conflits inutiles.

Tu pourras régler au fil de l'eau ton IDE en fonction des pratiques.
Pour l'instant, je recommande de récupérer cette section quizz, de l'inclure dans un fichier dédié `templates/blog/article_quizz.html.twig` et de [l'inclure](https://twig.symfony.com/doc/2.x/tags/include.html) ici après avoir revert le fichier.
Le fait de l'avoir dans un fichier distinct rendra ce fonctionnel plus visible et moins noyé dans la masse du reste du template article.

2021-09-02 07:55 UTC, ogizanagi commented on templates/blog/quiz.html.twig
> +</div>
Ce petit char rouge est rajouté par Github pour t'indiquer qu'il manque un saut de ligne final au fichier.
Tu dois pouvoir configurer ton IDE pour l'ajouter automatiquement normalement.

2026-04-13 07:50 UTC, closed without merging