Dynamic glossary
Elao/elao_ pull request #413
Opened 2021-09-21 09:30 UTC by Tom32i

Le glossaire dynamisé !

2021-09-21 12:01 UTC, ameliedefrance approved these changes
🎉

2021-09-21 17:40 UTC, ogizanagi commented on templates/glossary/index.html.twig
>          <div class="need-accompaniement">
Attention à ne pas oublier de câbler également la liste des articles sur cette page (ci dessous "Pour aller encore plus loin dans le quotidien d'un projet web, découvrez notre blog")

2021-09-24 12:59 UTC, cmozzati commented on templates/glossary/index.html.twig
>          <div class="need-accompaniement">
@Tom32i tu pourrais poser ça stp ? comme ça on pourra pousser la page dès la semaine prochaine discrétos 🙏

2021-09-24 12:59 UTC, cmozzati requested changes
Il manque juste la dynamisation des articles de blog 😊

2021-09-24 13:03 UTC, Tom32i commented on templates/glossary/index.html.twig
>          <div class="need-accompaniement">
@cmozzati  Du coup c'est quoi les specs ? On affiche quels articles ici ?

2021-09-24 13:04 UTC, cmozzati commented on templates/glossary/index.html.twig
>          <div class="need-accompaniement">
les derniers ni plus ni moins :)

2021-09-24 13:36 UTC, cmozzati approved these changes

2021-09-27 08:31 UTC, merged