[CONTENT] Add glossary links
Elao/elao_ pull request #595
Opened 2023-12-19 12:59 UTC by camille-cast

Closes https://github.com/Elao/interne/issues/230

2023-12-19 13:36 UTC, camille-cast commented on templates/site/approach/methodology.html.twig
> +                        <li><i class="icon icon--audit"></i><strong><a href="{{ path('glossary_term', {term: 'recette-fonctionnelle'}) }}">La recette fonctionnelle</a></strong></li>
**[ question ❓ ]** Sur l'issue concernée par la PR : https://github.com/Elao/interne/issues/230, 'recette fonctionnelle' est marqué comme devant avoir un lien ; or l'expression n'est que dans un ```<li>``` et est moyennement visible vu que les a sont en bleu turquoise sur le site, et le fond de ce panneau est en bleu foncé. 

Je ne sais pas si c'est essentielle de mettre ce lien ?

2023-12-19 13:36 UTC, camille-cast commented on templates/site/services/ia.html.twig
> +                    <p>Depuis plusieurs mois, les équipes d'Elao travaillent sur ce projet avec une idée en tête : permettre à nos clients d'exploiter toute puissance de <strong><a href="{{ path('glo
**[ question ❓ ]** l'expression"l'IA" est présente beaucoup de fois sur cette page, dans l'issue il n'est pas précisé combien de fois elle est sensée apparaître; est-ce que je mets bien le lien sur le glossaire sur toutes les occurrences ?

2023-12-19 13:36 UTC, camille-cast commented on templates/site/home.html.twig
> +                        <li><strong><a href="{{ path('glossary_term', {term: 'symfony'}) }}">Symfony</a></strong>, LE <strong>framework <a href="{{ path('glossary_term', {term: 'php'}) }}">PHP</a></s
**[note ✍️ ]** : Je me suis permise d'ajouter un lien vers la page glossaire 'PHP' même si ce n'était pas notifié dans l'issue

2023-12-19 13:53 UTC, camille-cast commented on templates/site/home.html.twig
> +                            <li><strong><a href="{{ path('glossary_term', {term: 'methodologie'}) }}">Méthodologie Agile (mais pas que)</a></strong></li>
**[note ✍️ ]** : J'ai aussi rajouté le lien vers la page glossaire 'méthodologies' ici, mais pas mentionné dans l'issue.

2023-12-19 13:53 UTC, camille-cast commented on templates/site/home.html.twig
> +                            <li>Expertise <strong><a href="{{ path('glossary_term', {term: 'devops'}) }}">DevOps</a></strong></li>
**[note ✍️ ]** : Pareil : j'ai rajouté le lien vers 'DevOps', pas cité dans l'issue.

2023-12-19 16:30 UTC, evaelao commented on templates/site/approach/methodology.html.twig
> +                        <li><i class="icon icon--audit"></i><strong><a href="{{ path('glossary_term', {term: 'recette-fonctionnelle'}) }}">La recette fonctionnelle</a></strong></li>
Oui tu as raison, on peut l'enlever (ou alors modifier la couleur du lien)

2023-12-19 18:09 UTC, camille-cast commented on templates/site/approach/methodology.html.twig
> +                                <p>Des ateliers de compréhension du besoin en présence de toute l’équipe technique, aboutissant à la création du <strong><a href="{{ path('glossary_term', {term: 'back
@evaelao J'ai cherché dans les variables de couleurs du thème du site, il n'y a pas vraiment de blanc, j'ai mis du violet qui est la 2e couleur de la marque Elao après le rouge ;

![Capture d’écran 2023-12-19 à 19 08 24](https://github.com/Elao/elao_/assets/113354068/09f9b414-ebb2-42c7-81c9-fdf3ecfa17cc)

2023-12-20 07:10 UTC, evaelao commented on templates/site/approach/methodology.html.twig
> +                                <p>Des ateliers de compréhension du besoin en présence de toute l’équipe technique, aboutissant à la création du <strong><a href="{{ path('glossary_term', {term: 'back
Yes ça me parait très bien 👍

2023-12-28 14:09 UTC, ameliedefrance requested changes
Quelques suggestions de couleur pour un contraste un peu plus tranché 🎨

2024-01-02 09:28 UTC, evaelao approved these changes

2024-01-02 10:12 UTC, merged